### PR TITLE
Fix: invalid resource puphpet:postgresql:db

### PR DESCRIPTION
**Pull request by clempat**

### CODE REVIEW

**Comment by jtreminio** [comment]
Hi!

What issue does this fix? Where did you run into a problem?

**Comment by clempat** [comment]
Hey,
Hum... Maybe I don't understand. On [this line](https://github.com/puphpet/puppet-puphpet/blob/master/manifests/php/xdebug.pp#L24), it is set `/usr/lib/php5/20131226-zts`
But I use `puphpet/debian75-x64` with nginx php-fpm and the path there is `/usr/lib/php5/20131226`

**Comment by clempat** [comment]
Hi,
I use postgresql and wanted to add one db there.

On fresh vagrant up I get: `Error: Invalid resource type puphpet::postgresql::db at /tmp/vagrant-puppet-3/manifests/nodes/Postgresql.pp:47`

Then I guess that the directory name need to match the class namespace.

**Comment by jtreminio** [comment]
Gotcha, I see it now.

Thanks!

**Comment by clempat** [comment]
Nice project by the way...

**Pull request merged**
