### PR TITLE
allow install nodejs for version 7,8,9

### PR DESCRIPTION
**Pull request by catalinux**
allow install nodejs for version 7,8,9

### CODE REVIEW

**Comment by catalinux** [comment]
It was tested for `bento/ubuntu-16.04` and `bento/centos-7`

**Comment by jtreminio** [comment]
So the reason I hadn't added this in was this: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Ubuntu 14.04 does not support node.js >= 6.

I wonder if having this difference between distros is worth it.

**Comment by catalinux** [comment]
Two observations:

**One**: It worked also for ubuntu 14. See this config: https://gist.github.com/anonymous/fe78a8beaa638297300e9c04943f3ea2
v7.10.1


If I change to 8, I would have:
 node --version
v8.9.4

For 9:
v9.4.0


**Two**

You merged this: https://github.com/puphpet/puphpet/pull/2707/files.  Choosing 7 or 8 would install 6 because of 
```
    '6'     => '6.x',
    '5'     => '5.x',
    '4'     => '4.x',
    default => '6.x',

**Comment by catalinux** [comment]
Also see: https://stackoverflow.com/questions/34974535/install-latest-nodejs-version-in-ubuntu-14-04

**Pull request merged**
