### PR TITLE
Fix latest Node.js v4.0 release

### LINKED ISSUE #23: Fix latest Node.js v4.0 stable release
Getting an error since the /dist/latest/SHASUMS.txt file has been renamed

### PR DESCRIPTION
**Pull request by MichaelMackus**
Fixes #23

### CODE REVIEW

**Comment by guiwoda** [comment]
+1

**Comment by MichaelMackus** [comment]
@jtreminio any way we can get this merged? Unable to provision with node.js due to this :(

:beer:

**Comment by bendoh** [comment]
Yes, this is very important. Let's get this merged please!

**Comment by marcaddeo** [comment]
@jtreminio also having this issue, anyway we can get this into master ASAP? It's effecting our workflow.

**Comment by jtreminio** [comment]
Fixed by f8c1e18f6595630e6363bb1cc682de883eef95e1

**Pull request closed without merging**
