### PR TITLE
Use prefix php-* for some extensions on Ubuntu PHP 5.6/7

### PR DESCRIPTION
**Pull request by StudioMaX**
Fixed php extensions:
- apcu
- geoip
- imagick
- memcache
- memcached
- mongodb
- redis

Fixes https://github.com/puphpet/puphpet/issues/2163 https://github.com/puphpet/puphpet/issues/2162 https://github.com/puphpet/puphpet/issues/2158 https://github.com/puphpet/puphpet/issues/2145

### CODE REVIEW

**Comment by MatthewBooth** [comment]
This could do with merging in desperately as new PHP boxes are broken without this.

**Comment by fnagel** [comment]
Fix works for me. Merge would be appreciated.

**Comment by burzum** [comment]
+1 Please merge it!

**Comment by bensinclair** [comment]
+1

**Comment by StudioMaX** [comment]
ping @jtreminio

**Comment by marcintabaka** [comment]
+1

**Comment by qzxc** [comment]
+1 ping @jtreminio New PHP boxes are broken without this.

**Comment by svycka** [comment]
mcrypt also could be added

**Comment by jtreminio** [comment]
Thanks!

**Pull request merged**
